<?php

use Drupal\menu_link_content\Entity\MenuLinkContent;

  $links = \Drupal::entityTypeManager()->getStorage('menu_link_content')
  ->loadByProperties(['title' => 'File Upload']);

if($link = reset($links)) {

}

else{
 $menu_link = MenuLinkContent::create([
    'title' => 'File Upload',
    'link' => ['uri' => 'internal:/uniview8/fileupload'],
    'menu_name' => 'main',
    'expanded' => FALSE,
  ]);
  $menu_link->save();
}
?>



