<?php
 

 
namespace Drupal\uniview8_hdfcebs\Form;
 
use Drupal\Core\Form\ConfigFormBase;
 
use Drupal\Core\Form\FormStateInterface;
 
class ConfigForm extends ConfigFormBase {
 
  
 
  public function getFormId() {
 
    return 'config_form';
 
  }
 
 
 
  public function buildForm(array $form, FormStateInterface $form_state){

 $form = parent::buildForm($form, $form_state);
 
    $config = $this->config('hdfcebs.settings');

    $form['hdfc_ebs_requesturl'] = array(
      '#type' => 'textfield',
      '#title' => t('HDFEBS REQUEST URL'),
      '#description' => 'URL provided by EBS',
      '#default_value' => $config->get('hdfc_ebs_requesturl'),
      '#required' => TRUE,
  );
  $form['hdfc_ebs_return_url'] = array(
      '#type' => 'textfield',
      '#title' => t('RETURN URL'),
      '#description' => 'the url you want the payment gateway to return back after transaction is successful',
      '#default_value' => $config->get('hdfc_ebs_return_url'),
      '#required' => TRUE,
  );
  $form['hdfc_ebs_secretkey'] = array(
      '#type' => 'textfield',
      '#title' => t('SECRET KEY'),
      '#description' => 'Secret Key provided by the ebs Payment Gateway used for calculating hash. ',
      '#default_value' => $config->get('hdfc_ebs_secretkey'),
      '#required' => TRUE,
  );
  $form['hdfc_ebs_channel'] = array(
      '#type' => 'textfield',
      '#title' => t('CHANNEL'),
      '#description' => 'The payment channel. Give ‘10’ for Standard',
      '#default_value' => $config->get('hdfc_ebs_channel'),
      '#required' => TRUE,
  );
  $form['hdfc_ebs_accountid'] = array(
      '#type' => 'textfield',
      '#title' => t('ACCOUNT ID'),
      '#description' => 'Your Account ID  generated by ebs Bank. ',
      '#default_value' => $config->get('hdfc_ebs_accountid'),
      '#required' => TRUE,
  );
  $form['hdfc_ebs_mode'] = array(
      '#type' => 'textfield',
      '#title' => t('MODE'),
      '#description' => 'Mode of payment should be LIVE. ',
      '#default_value' => $config->get('hdfc_ebs_mode'),
      '#required' => TRUE,
  );
  $form['hdfc_ebs_currency'] = array(
      '#type' => 'textfield',
      '#title' => t('CURRENCY'),
      '#description' => 'Curreny INR. ',
      '#default_value' => $config->get('hdfc_ebs_currency'),
      '#required' => TRUE,
  );
  $form['hdfc_ebs_pageid'] = array(
      '#type' => 'textfield',
      '#title' => t('PAGE ID'),
      '#description' => 'The id of the customized page. ',
      '#default_value' => $config->get('hdfc_ebs_pageid'),
      '#required' => TRUE,
  );
  $form['hdfc_ebs_pageid'] = array(
      '#type' => 'textfield',
      '#title' => t('PAGE ID'),
      '#description' => 'The id of the customized page. ',
      '#default_value' => $config->get('hdfc_ebs_pageid'),
      '#required' => TRUE,
  );
 $form['hdfc_ebs_paymentoption'] = array(
      '#type' => 'checkboxes',
      '#title' => t('PAYMENT OPTION'),
      '#options' => array('1001' => 'Test', 'Credit' => 'Credit', 'Debit' => 'Debit', 'Cash' => 'Cash', 'Net Banking' => 'Net Banking',  'EMI' => 'EMI'),
      '#default_value' => $config->get('hdfc_ebs_paymentoption'),
      '#description' => t('Note : 1001 is TEST. When this is enabled, others should not be.'),
      '#required' => TRUE,
    );

  
 $node_types = \Drupal\node\Entity\NodeType::loadMultiple();
 
    $node_type_titles = array();
 
    foreach ($node_types as $machine_name => $val) {
 
      $node_type_titles[$machine_name] = $val->label();
 
    }
 


   return $form;  
}

 
  public function submitForm(array &$form, FormStateInterface $form_state) {
 
    $config = $this->config('hdfcebs.settings');
 
$config->set('hdfc_ebs_requesturl', $form_state->getValue('hdfc_ebs_requesturl'));
$config->set('hdfc_ebs_return_url', $form_state->getValue('hdfc_ebs_return_url'));
$config->set('hdfc_ebs_secretkey', $form_state->getValue('hdfc_ebs_secretkey'));
$config->set('hdfc_ebs_channel', $form_state->getValue('hdfc_ebs_channel'));
$config->set('hdfc_ebs_accountid', $form_state->getValue('hdfc_ebs_accountid'));
$config->set('hdfc_ebs_mode', $form_state->getValue('hdfc_ebs_mode'));
$config->set('hdfc_ebs_currency', $form_state->getValue('hdfc_ebs_currency'));
$config->set('hdfc_ebs_pageid', $form_state->getValue('hdfc_ebs_pageid'));
$config->set('hdfc_ebs_paymentoption', $form_state->getValue('hdfc_ebs_paymentoption'));

  \Drupal::service('config.factory')->getEditable('foo.bar')->set('foo', 'foo')->save(); 
 
    $config->save();



 
    return parent::submitForm($form, $form_state);
 
  }
 

  protected function getEditableConfigNames() {
 
    return [
 
      'hdfcebs.settings',
 
    ];
 
  }
 
}
